spring:
  application:
    name: oauth-sb-student

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            redirectUri: ${REDIRECT}
            authorizationUri: "https://accounts.google.com/o/oauth2/v2/auth"
            tokenUri: "https://www.googleapis.com/oauth2/v4/token"
            userInfoUri: "https://www.googleapis.com/oauth2/v3/userinfo"
            jwkSetUri: "https://www.googleapis.com/oauth2/v3/certs"
            clientName: "Google"
            scope:
              - email
              - profile
              - phone
